import NavBar from "./components/NavBar";
import "./globals.css";
import { Analytics } from "@vercel/analytics/react";
import { SpeedInsights } from "@vercel/speed-insights/next";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({ children }) {
  return (
    <html lang="en" className="dark">
      <head>
        <meta
          name="google-site-verification"
          //content="r_m0EEK6mbjStYggwq2kM_YuQ8Ab3BpZGY0mnDHeWkM"
          content="wgyXgpMHZM9gx6gN7acoFoTPX9RL5Hkk"
        />
      </head>
      <body
        className="bg-[#ECEFF1] dark:bg-gray-900 scrollbar-hide"
        suppressHydrationWarning={true}
      >
        <NavBar>{children}</NavBar>
        <Analytics />
        <SpeedInsights />
      </body>
    </html>
  );
}
